# Generated by Django 2.0 on 2020-03-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referee', '0001_initial'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField()),
                ('score_team_one', models.IntegerField()),
                ('score_team_second', models.IntegerField()),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.Goal')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.Referee')),
            ],
        ),
    ]
