# Generated by Django 3.0.5 on 2020-04-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200307_1409'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='goals',
        ),
        migrations.AddField(
            model_name='game',
            name='first_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='team.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='isActiveGame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='second_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='team.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='score_team_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_team_second',
            field=models.IntegerField(default=0),
        ),
    ]
