# Generated by Django 2.0 on 2020-02-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_auto_20200217_0141'),
        ('referee', '0001_initial'),
        ('game', '0002_auto_20200217_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='goals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goal.Goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='referee.Referee'),
            preserve_default=False,
        ),
    ]
