# Generated by Django 2.0 on 2020-03-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTime', models.IntegerField()),
                ('assistPlayer', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='assist_player', to='player.Player')),
                ('goalPlayer', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='goaler_player', to='player.Player')),
            ],
        ),
    ]
