# Generated by Django 2.0 on 2020-02-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200217_0059'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goalPlayer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
