# Generated by Django 3.0.5 on 2020-04-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200406_1650'),
        ('game', '0002_auto_20200407_1710'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalPlayer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='goal_player', to='player.Player'),
        ),
    ]
