# Generated by Django 2.0 on 2020-02-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200217_0059'),
        ('goal', '0002_goal_goalplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assistPlayer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='assist_player', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalPlayer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='goaler_player', to='player.Player'),
        ),
    ]
