# Generated by Django 2.0 on 2020-02-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistica',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='played_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='red_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='yellow_card',
            field=models.IntegerField(default=0),
        ),
    ]
