# Generated by Django 3.0.5 on 2020-04-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '__first__'),
        ('_auth', '0002_remove_myuser_favouritematches'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favouriteMatches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
