# Generated by Django 3.0.5 on 2020-04-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '__first__'),
        ('_auth', '0002_notificaiton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaiton',
            new_name='Notification',
        ),
    ]
