# Generated by Django 3.0.5 on 2020-04-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_auto_20200425_2109'),
        ('_auth', '0003_myuser_favouritematches'),
    ]

    operations = [
    ]
