# Generated by Django 3.0.5 on 2020-04-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200307_1409'),
        ('statistica', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='statistica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statistica.Statistica'),
        ),
    ]
