# Generated by Django 2.0 on 2020-02-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistica', '0001_initial'),
        ('player', '0003_auto_20200214_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='statistica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistica.Statistica'),
            preserve_default=False,
        ),
    ]
