# Generated by Django 3.0.5 on 2020-04-25 17:24

from django.db import migrations, models
import django.db.models.deletion
import football_app.player.models


class Migration(migrations.Migration):

    dependencies = [
        ('statistica', '0001_initial'),
        ('player', '0003_playerfullinfo_player_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='statistica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statistica.Statistica'),
        ),
        migrations.AlterField(
            model_name='playerfullinfo',
            name='player_info',
            field=models.FileField(blank=True, null=True, upload_to='files', validators=[football_app.player.models.validate_file_size, football_app.player.models.validate_extension]),
        ),
    ]
