# Generated by Django 3.0.5 on 2020-04-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        ('country', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('logo', models.ImageField(default='https://images.alphacoders.com/105/1056501.jpg', upload_to='photos/')),
                ('wins', models.IntegerField(blank=True, default=0)),
                ('draws', models.IntegerField(blank=True, default=0)),
                ('losts', models.IntegerField(blank=True, default=0)),
                ('point', models.IntegerField(blank=True, default=0)),
                ('lasts_5', models.CharField(default='', max_length=100)),
                ('goal_difference', models.IntegerField(blank=True, default=0)),
                ('short_code', models.CharField(blank=True, default='', max_length=100)),
                ('coach', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coach.Coach')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
                ('league', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
    ]
