# Generated by Django 3.0.5 on 2020-04-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(default=None, max_length=100)),
                ('logo', models.ImageField(default='https://toplogos.ru/images/logo-uefa-champions-league.jpg', upload_to='photos/')),
                ('seasonStart', models.DateTimeField(default=None)),
                ('seasonEnd', models.DateTimeField(default=None)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='country.Country')),
            ],
        ),
    ]
