# Generated by Django 2.0 on 2020-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(default='https://toplogos.ru/images/logo-uefa-champions-league.jpg', upload_to='photos/'),
        ),
    ]
