# Generated by Django 3.0.5 on 2020-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200426_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='seasonEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='seasonStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
