# Generated by Django 2.0 on 2020-03-10 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200307_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='country.Country'),
        ),
        migrations.AlterField(
            model_name='league',
            name='seasonEnd',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 12, 37, 56, 189913)),
        ),
        migrations.AlterField(
            model_name='league',
            name='seasonStart',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 12, 37, 56, 189913)),
        ),
    ]
