# Generated by Django 3.0.5 on 2020-04-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20200310_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='seasonEnd',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='league',
            name='seasonStart',
            field=models.DateTimeField(default=None),
        ),
    ]
