# Generated by Django 2.0 on 2020-03-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('date_of_birth', models.DateField(default=None)),
                ('salary', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
