# Generated by Django 3.0.5 on 2020-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default=None, max_length=100)),
                ('flag', models.ImageField(default='https://www.akorda.kz/upload/content_files/simbols/flag.png', upload_to='photos/')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
    ]
