# Generated by Django 2.0 on 2020-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='https://www.akorda.kz/upload/content_files/simbols/flag.png', upload_to='photos/'),
        ),
    ]
