# Generated by Django 2.0 on 2020-03-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200307_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
